# -*- coding: utf-8 -*-
"""Copia de Confidence intervals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mQLc6SyzoGTcSJVPLpDUKf2P-r71q4R2

# Confidence intervals
"""

import numpy as np
from scipy import stats
from IPython.display import display, Markdown

#M = [63.2, 69.7, 67.3, 64.8, 72]
M = [3.30, 3.04, 4.07, 3.06, 3.85, 3.12, 3.36, 3.24, 4.57, 3.02]

reps = len(M)

print("Rep.\tAverage waiting time of those who waited:")
for i in range(0, len(M)):
    print("%d\t%g" % (i+1,M[i]), sep=' ', end='\n')

alpha = 0.01
confidence = (1-alpha)*100

mean = np.mean(M)
var = np.var(M,ddof=1)
desv = np.sqrt(var)

tval = stats.t.ppf(1-(alpha/2), reps-1)
hval = tval*(desv/np.sqrt(reps))

display(Markdown(
   rf"""
${confidence}\%$ confidence

$\bar{{X}} = {mean}$

$S = {desv}$

$t_{{n-1,1-\frac{{\alpha}}{2}}} = t_{{{reps-1},{1-alpha/2}}} ={tval}$

$h = {hval}$

Intervalo de confianza : $C.I. = (\bar{{X}}-h , \bar{{X}} + h) = ({mean-hval},{mean+hval})$

"""))

